### ISSUE TITLE
update pravega submodule to the latest master commit

### ISSUE THREAD

**Issue by vijikarthi** [pravega/flink-connectors#112]
**Problem description**
The pravega sub-module in the connector project is pointing to a old commit which needs to be refreshed to latest master commit. Fix any issues that may arise due to any changes to Pravega client code (streamcuts API) .

**Comment by EronWright** [comment]
While doing this, please check for any new sub-projects and update the dependency substitution list accordingly, thanks.  I know there's a new authplugin module.
