### ISSUE TITLE
Harden the Pravega dependency version against external influence

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#113]
**Problem description**
Dependency versioning improves stability by explicitly building against the version that the code was designed for.  Pravega provides no compatibility guarantees for its client API at this time.   The connector build script should resist external influence over the Pravega dependency. 

**Suggestions for an improvement**
Eliminate the `pravegaVersion` variable.

**Comment by fpj** [comment]
I don't fully understand this issue. It refers to compatibility of the client API, but suggests to remove `pravegaVersion`. I'd like to understand what the precise problem is that we are trying to solve here and how removing `pravegaVersion` solves it.

**Comment by EronWright** [comment]
To elaborate on the issue, the `pravegaVersion` variable exists to centralize the value across numerous locations in the build script.   In my opinion it should be considered to have 'private' access (in a Java sense), as opposed to 'public' access as though it were intended to be set by application code. 

The rationale is, at any given point in time, the connector depends on specific versions of Flink, Pravega, Guava, etc.   The legitimate ways to change the version of a dependency are to:
