### ISSUE TITLE
Update default transaction timeouts in FlinkPravegaWriter to sync with Pravega defaults

### ISSUE THREAD

**Issue by vijikarthi** [pravega/flink-connectors#126]
**Problem description**
For the Exactly once writer, the default transaction grace period timeout is more than the allowed limit.

```
java.util.concurrent.CompletionException: io.pravega.shaded.io.grpc.StatusRuntimeException: INTERNAL: scaleGracePeriod too large, max value is 30000
```

**Problem location**
`FlinkPravegaWriter` implementation

https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java#L64

**Comment by fpj** [comment]
This timeout will actually go away once we implement rolling txns.

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/flink-connectors/pull/147
