### ISSUE TITLE
Add pravega client dependency to connector POM

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#145]
**Problem description**
The Pravega client is currently shaded but not relocated in the connector JAR, and is not mentioned in the effective POM.  This is an odd situation, because an application that links to the connector is not told that Pravega is included, yet it is, or what version is included.   The application may well need to use the client directly, for example the pravega samples pre-create a scope in their main method.

Adding the client dependency is not as simple as it sounds, however.    If the connector were to have a straightforward dependency on the Pravega client in its effective POM, the application would see it as a transitive dependency and include it in its own uberjar _without the shading that is normally required_.    The true prerequisite is pravega/pravega#1339 (Pravega client to shade its dependencies), which would vastly simplify both the connector and the application.

**Problem location**

**Suggestions for an improvement**
- fix pravega/pravega#1339
- eliminate shading logic in connector 
- declare pravega client dependency

**Comment by EronWright** [comment]
@yangb8 this is an issue that affects the hadoop-connector too.

**Comment by yangb8** [comment]
Thanks for letting me know, will create issue and work on it
