### ISSUE TITLE
Support timestamp rows with FlinkPravegaTableSource

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#146]
**Problem description**
@claudiofahey reports that there's no clear way to designate a particular column as timestamp-bearing, for the purposes of timestamp assignment / watermark generation.   Investigate whether there's generic support in the Table API or what must minimally be done.   Also see [`Kafka010JsonTableSource::setProctimeAttribute`](https://ci.apache.org/projects/flink/flink-docs-release-1.4/api/java/org/apache/flink/streaming/connectors/kafka/Kafka010JsonTableSource.html#setProctimeAttribute-java.lang.String-).

**Problem location**

**Suggestions for an improvement**

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/flink-connectors/pull/177
