### ISSUE TITLE
Implement Flink `TableFactory`

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#181]
**Problem description**
Flink provides a pure-SQL way to load table sources and sinks.  One reason is to support the new Flink [SQL Client Shell](https://ci.apache.org/projects/flink/flink-docs-stable/dev/table/sqlClient.html).

There's a new `TableFactory` interface that must be implemented ([ref](https://ci.apache.org/projects/flink/flink-docs-master/dev/table/sourceSinks.html#define-a-tablefactory)).  A TableFactory makes it possible to create sources purely from string-based properties.

See related documentation about so-called [environment files for SQL Client](https://ci.apache.org/projects/flink/flink-docs-release-1.6/dev/table/sqlClient.html#environment-files).

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/flink-connectors/pull/205
