### ISSUE TITLE
Table API: factor out the table connector from the table format

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#182]
**Problem description**
Related to #181 , the 'unified' connection API for table sources/sinks allows the format of the data to be decoupled from the connector.   In other words, we don't need `FlinkPravegaJsonTableSource` (a subclass of `FlinkPravegaTableSource`), we need to create a subclass of `org.apache.flink.table.descriptors.ConnectorDescriptor`, and users will be able to use a standard table format (json, avro, etc.).

Here's an example of a table factory that uses `TableFactoryService` to find the configured `DeserializationSchema`:
https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/streaming/connectors/kafka/KafkaTableSourceSinkFactoryBase.java

See: https://ci.apache.org/projects/flink/flink-docs-master/dev/table/connect.html

**Problem location**

**Suggestions for an improvement**

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/flink-connectors/pull/205
