### ISSUE TITLE
Use a stable default readerName

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#19]
**Problem description**
The `readerName` is used only as a key into Flink's checkpoint state to disambiguate the state written by our checkpoint hook, from that of other hooks in the same job.    It is important for the value to be stable, otherwise the savepoint is unusable.   Let's use a more stable identifier by default than a randomly-generated value.

**Problem location**
FlinkPravegaReader

**Suggestions for an improvement**
Ordinary state stored by an operator is similarly disambiguated using the operator ID ([ref](https://ci.apache.org/projects/flink/flink-docs-master/api/java/org/apache/flink/streaming/api/datastream/SingleOutputStreamOperator.html#uid-java.lang.String-)).    Some enhancement to Flink's hook facility would be needed to use the operator ID here.   

In the meantime, I suggest hashing the inputs to the PravegaFlinkReader (stream name, etc) to generate a default value for the `readerName`.

**Comment by vijikarthi** [comment]
What is the rationale (why do we need) in providing a constructor without reader name?
https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java#L110
