### ISSUE TITLE
Update connector to support Flink 1.7

### ISSUE THREAD

**Issue by vijikarthi** [pravega/flink-connectors#212]
**Problem description**
Update flink connector to support [Flink 1.7.0](https://flink.apache.org/news/2018/11/30/release-1.7.0.html). As part of this change, update scala support from `2.11` to `2.12`. This means that Flink connector by default will publish artifacts that supports scala `2.12.` 

**Problem location**
Connector repository - build scripts

**Suggestions for an improvement**
Provide documentation in the connector repo on how to build connector using scala `2.11` in case if the user plans to build the artifacts from the source.

**Comment by fpompermaier** [comment]
It would be nice to also publish this connector to the maven central repo..

**Comment by vijikarthi** [comment]
@fpompermaier yes we publish the connector artifacts to Maven (release version) and JCenter (snapshots)

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/flink-connectors/pull/223
