### ISSUE TITLE
Update Pravega version to latest master

### ISSUE THREAD

**Issue by vijikarthi** [pravega/flink-connectors#241]
**Problem description**
Update Pravega version to `0.6.0-50.51c766c-SNAPSHOT` and bump the sub-module commit to `51c766c126b184a6d93f09115c1907f697bb15ee`

**Problem location**
Build configurations

**Suggestions for an improvement**

**Comment by jkhalack** [comment]
It would be nice to update pravega on `r0.5` branch too.
