### ISSUE TITLE
Add logging support to tests

### ISSUE THREAD

**Issue by fpj** [pravega/flink-connectors#25]
**Problem description**
All tests are currently timing out in my setup. I went to build looking for logs and didn't find any. It would be useful to have slf4j logging dumped by default to files so that we can inspect in the case of test failures.

**Problem location**
Tests, logging.

**Suggestions for an improvement**
Add slf4j logging and configuration.

**Comment by EronWright** [comment]
Investigated a bit.  The tests normally pick up `src/test/resources/logback.xml` which enables logging to standard out.  However, the gradle test task is presently configured to ignore standard out.  To get log lines to the console:
1. edit `gradle/java.gradle`
2. set `showStandardStreams` to `true`
3. set `testLogging.events` to `["PASSED", "FAILED", "STANDARD_OUT"]`

I don't know whether this is a good idea.  @fpj what do you think?
