### ISSUE TITLE
Update Pravega version in r0.5

### ISSUE THREAD

**Issue by fpj** [pravega/flink-connectors#250]
**Problem description**
Update Pravega version in r0.5 branch to the latest commit `352da549e729cadf49b88c043d6acd4818045f33` and the corresponding snapshot version to `0.5.0-2300.352da54-SNAPSHOT`.

**Problem location**
Connector r0.5 branch build configurations

**Suggestions for an improvement**

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/flink-connectors/pull/251
