### ISSUE TITLE
Update Connector version to 0.5.1

### ISSUE THREAD

**Issue by crazyzhou** [pravega/flink-connectors#267]
**Problem description**

In preparation of the connector release, update connector version to `0.5.1` from the `r0.5` branch in support of Pravega release `0.5.1` ( https://github.com/pravega/pravega/releases/tag/v0.5.1)

Update Pravega version from gradle.properties to `0.5.1`
Update Connector version from gradle.properties to `0.5.1`
Update Pravega sub-module commit ID to `35797c05455a5d05c8af5782557e8f986d47c2df`

**Problem location**
Build scripts

**Suggestions for an improvement**

**Comment by fpj** [comment]
Pravega `0.5.1` is released, we should cut a new version of the connector too.
