### ISSUE TITLE
[Ask for a help] A survey of ExternallyInducedSource or WithMasterCheckpointHook of Flink

### ISSUE THREAD

**Issue by ifndef-SleePy** [pravega/flink-connectors#287]
Hi guys,

I'm a contributor from Flink community. I'm doing some refactoring of `CheckpointCoordinator` of Flink [1]. Someone reminds me that it might be relevant to your project. So I'm here to ask you guys. You could find more background infos in [2]. 

I'm refactoring the threading model of `CheckpointCoordinator`. The thread which `MasterTriggerRestoreHook.triggerCheckpoint` is executed in might be changed. One of the options of refactoring is that keeping the compatibility but the `MasterTriggerRestoreHook.triggerCheckpoint` must be executed in a non-blocking way. Because it will be executed in a performance sensitive thread.

I have taken a look at codes of this project roughly. It seems that the implementation `ReaderCheckpointHook` satisfies the requirement of "non-blocking" well. Could anyone do me a favor to double check it?

Please give me a feedback if you guys have any concern or idea. Thanks!

[1] https://issues.apache.org/jira/browse/FLINK-13698
[2] http://apache-flink-mailing-list-archive.1008284.n3.nabble.com/SURVEY-How-do-you-use-ExternallyInducedSource-or-WithMasterCheckpointHook-td33864.html

**Comment by crazyzhou** [comment]
Yes, we keep it "non-blocking", it will turn to another thread pool to run `CompletableFuture.cancel` after a 5-second timeout in order to prevent blocking calls. Any other comments? @EronWright and @maddisondavid

**Comment by ifndef-SleePy** [comment]
Hi @crazyzhou , thanks for feedback. It helps a lot!

BTW, there is another question, does it depend on sequential order of `triggerCheckpoint` of master hook and task state?
Currently Flink triggers checkpoint of task state after finishing master hook checkpoint (the `CompletableFuture` returned is completed). Is any problem of your project if Flink snapshots master hook and task state concurrently?

**Comment by crazyzhou** [comment]
No, it doesn't. It'll be nice to have them concurrent.

**Comment by EronWright** [comment]
PR: https://github.com/apache/flink/pull/9885

**Comment by EronWright** [comment]
@ifndef-SleePy do you anticipate any changes required in this connector, for Flink 1.10?

**Comment by ifndef-SleePy** [comment]
@EronWright , no, we keep the compatibility. The only thing changed is the thread which master hook executes in. I believe it's all right with this connector.
BTW, @crazyzhou , glad to hear that. Maybe we could make it concurrent in the future.

**Comment by AlexanderZhao1** [comment]
@ifndef-SleePy  
Hello! We are recently updating Flink-connectors with Flink 1.10 version. Unfortunately, we encountered some problems in our test case:

Location: java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

```java
@Test
    public void testNonTransactionalWriterSnapshot() throws Exception {
        try (NonTransactionalWriterTestContext context = new NonTransactionalWriterTestContext(false, PravegaWriterMode.ATLEAST_ONCE)) {
            try (StreamSinkOperatorTestHarness<Integer> testHarness = createTestHarness(context.sinkFunction)) {
                testHarness.open();
                FlinkPravegaWriter.NonTransactionalWriter internalWriter = (FlinkPravegaWriter.NonTransactionalWriter) context.sinkFunction.writer;
                // take a snapshot
                testHarness.snapshot(1L, 1L);

                // simulate a write error
                internalWriter.writeError.set(new IntentionalRuntimeException());

                // take another snapshot, expecting it to fail
                try {
                    testHarness.snapshot(2L, 2L);
                    Assert.fail("expected an exception due to a prior write error");
                } catch (Exception ex) {
                    Assert.assertNotNull(ex.getCause());
                    Assert.assertTrue(ex.getCause() instanceof IOException);
                    Assert.assertTrue(ex.getCause().getCause() instanceof IntentionalRuntimeException);
                }
                // clear the error for test simplicity
                internalWriter.writeError.set(null);
            }
        }
    }
```

In this testcase we simulate a write error during taking flink snapshot , and we expect the exception we catch is 
`org.apache.flink.runtime.checkpoint.CheckpointException`
and `ex.getCause()` is `java.io.IOException`. 

So the code `Assert.assertTrue(ex.getCause() instanceof IOException);` will pass successfully right?(It works in Flink 1.9)

But what we found in 1.10 is that this assertion doesn't work, although I found that `ex.getCause()` is still `java.io.IOException` in debug mode.
So I use `ex.getCause().getClass()` to check which class it belongs to, and it shows that it belongs to `org.apache.flink.util.SerializedThrowable`.

So I wonder does the refactoring of CheckpointHook or other codes change the CheckpointException or its rootCause?

 @crazyzhou for reference.

**Comment by ifndef-SleePy** [comment]
Hi @AlexanderZhao1 ,

**Comment by crazyzhou** [comment]
Thanks, @ifndef-SleePy . We have addressed your suggestions here: https://github.com/pravega/flink-connectors/pull/342/files#diff-fa5418d909c3a6d1e0e87fa34af94434R368. Could you also help or find someone appropiate on this issue #341 we met in 1.10 upgrade?

**Comment by ifndef-SleePy** [comment]
Hi @crazyzhou , thanks for feedback. I took a look at the #341 issue, however I'm not an expert in table api/sql. I'm afraid the guys you @ might not be familiar with it either. Have you ever reached out through mailing list (dev or user)?

**Comment by crazyzhou** [comment]
The exactly-once feature going well with the new checkpoint during Flink 1.10 tests. Thus, close this issue. Thanks the Flink community for the information.
