### ISSUE TITLE
Don't emit a final watermark when source is stopped

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#288]
**Problem description**
It is wrong to emit a final watermark when a source is cancelled, because it would prevent a savepoint from being useful for continuation purposes.   Only in the case of a bounded source would this behavior be correct.  I think there's a flink cli command which stops and emits the final watermark, as an alternative (will investigate).

**Problem location**
https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java#L300

**Suggestions for an improvement**

**Comment by crazyzhou** [comment]
Agreed with Eron. Noticed this comment by whether to add it. https://github.com/apache/flink/blob/fd511c345eac31f03b801ff19dbf1f8c86aae760/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamSource.java#L102-L105
