### ISSUE TITLE
Refactor deprecated Pravega client API for 0.7

### ISSUE THREAD

**Issue by crazyzhou** [pravega/flink-connectors#304]
**Problem description**
In Pravega 0.7, we will do the folowing removals
- Removes ClientFactory (Replaced by EventStreamClientFactory)
- Removes beginTxn() and getTxn() methods from the EventStreamWriter. (Replaced by methods on TransactionalEventStreamWriter)
- Removes the ByteStreamClient interface. (Replaced by ByteStreamClientFactory)

**Problem location**
Client usage

**Suggestions for an improvement**

**Comment by crazyzhou** [comment]
Checked the code, we have no usage of these classes and methods, so close this issue.

**Comment by shrids** [comment]
https://github.com/pravega/flink-connectors/blob/14bf66fddce8b7297286ebaa70f5daa8d8dfbc3b/src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java#L107 uses a deprecated api.
