### ISSUE TITLE
Build error - Could not find zookeeper-tests.jar

### ISSUE THREAD

**Issue by claudiofahey** [pravega/flink-connectors#309]
**Problem description**
```
git clone --recursive https://github.com/pravega/flink-connectors.git
./gradlew clean build
```
Output:
```
> Task :compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':testCompileClasspath'.
> Could not find zookeeper-tests.jar (org.apache.zookeeper:zookeeper:3.5.3-beta).
  Searched in the following locations:
      file:/home/faheyc/.m2/repository/org/apache/zookeeper/zookeeper/3.5.3-beta/zookeeper-3.5.3-beta-tests.jar
```

**Problem location**
build.gradle

**Suggestions for an improvement**
Add necessary dependency.

**Comment by claudiofahey** [comment]
```
java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

**Comment by crazyzhou** [comment]
As I can find in http://oss.jfrog.org/jfrog-dependencies/org/apache/zookeeper/zookeeper/3.5.3-beta/, the test jar is located there. I would assume if it's the issue for your local maven resolving as I can see it only searched in your local maven repository. Could you please try to delete the local zookeeper folder in the repository to force a remote search?

**Comment by claudiofahey** [comment]
This problem was fixed by deleting the directory /home/faheyc/.m2/repository/org/apache/zookeeper on my build machine. This was not a problem with this connector.
