### ISSUE TITLE
Add test case for JsonSerializer

### ISSUE THREAD

**Issue by crazyzhou** [pravega/flink-connectors#333]
**Problem description**
We need test cases to check the correctness of the `io.pravega.connectors.flink.serialization.JsonSerializer`

**Problem location**
`PravegaSerializationTest`

**Suggestions for an improvement**
Add a test case to prove the indempotency of `JsonSerializer`

**Comment by crazyzhou** [comment]
Since the `JsonSerializer` here is a Pravega serializer, another approach which I think would be better would be putting this class and test into the Pravega code base. We can just put it in `io.pravega.client.stream.impl`, the same directory with `JavaSerializer`. @fpj

**Comment by fpj** [comment]
We are talking about the code in this class not being covered in tests, right?

https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/serialization/JsonSerializer.java

This file is part of `pravega/flink-connectors`, so why would we test it in the `pravega/pravega` repo? Just add one or more test cases to cover the code in that class that is not being covered. Check the codecov report in the PR #332 .

**Comment by crazyzhou** [comment]
We can leave the `JsonSerializer` as-is. #334 is raised to fix the test.
