### ISSUE TITLE
Inclusive vs. Exclusive Watermarks

### ISSUE THREAD

**Issue by fpj** [pravega/flink-connectors#343]
**Problem description**
The code of `LowerBoundAssigner` subtracts one from the lower bound to determine the watermark:

https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/watermark/LowerBoundAssigner.java#L25

It sounds like that was done this way so that the watermark is inclusive, inclusive in the sense that the low watermark _t_ indicates that all events with timestamps smaller or equal to _t_ have been read. That's is confusing, though, and it does not seem aligned with how Flink deals with watermarks.

To explain the issue, let me describe the problem I came across. In my experiment, I created 50 files with 1,000 events in each file. To simplify the time assignment, I have assigned the same timestamp to all events in a file, and the timestamp is the file number. The watermark here is supposed to represent the progression of files. I have some simple window aggregation and each window corresponds to processing the events with a single timestamp (same file).

If I note time at the end of each file with the file number representing time, then after processing all files, I only get 49 windows processed, and that's because the watermark never progresses beyond the value that closes the last window because we are subtracting -1L.

I did a second experiment to validate that I get all windows processed when I use file number + 1. In that case, I eventually get a watermark that is equal to the number of the last file and I get all expected windows processed.

According to my evaluation, Flink treats the watermark in an inclusive manner, like I defined above. If so, we should remove the -1 subtraction to comply with that expectation.

**Problem location**
`LowerBoundAssigner`

**Suggestions for an improvement**
Remove the subtraction.

**Comment by crazyzhou** [comment]
Yes, I would agree with you. In fact, I also had doubts of the substraction when I implemented that. I will change that.
