### ISSUE TITLE
Make `writer.enable-watermark` optional in Table API properties

### ISSUE THREAD

**Issue by crazyzhou** [pravega/flink-connectors#364]
**Problem description**
In the current code of Table API,  `writer.enable-watermark` is required. It means that when users are using Flink SQL client with a YAML environmental file, or create a sink with properties map, the `writer.enabled-watermark` section is required explicitly.
As the best practice similar with other connectors https://ci.apache.org/projects/flink/flink-docs-release-1.10/dev/table/connect.html , we should put this optional feature as an optional property in the map. 
This also makes our current documentation of the Table API [here](https://github.com/pravega/flink-connectors/blob/master/documentation/src/docs/table-api.md#sample-environment-file) correct without getting exception of missing the required property: `writer.enable-watermark`. The document upgrade will be addressed in #357 

**Problem location**
Table API

**Suggestions for an improvement**
Should change it to `Optional<Boolean>`.

**Comment by fpj** [comment]
I don't understand the description of this issue. It indicates that a configuration parameter is required, but I don't understand whether that's required to be true to simply configured. And, it concludes that it needs to be optional. I don't follow the reasoning.

Also, there was no assignee even though there is a PR, and there are no labels. Please update this issue and elaborate on why the change is needed.

**Comment by crazyzhou** [comment]
I updated the description with the elaboration and added labels for this issue.
