### ISSUE TITLE
PravegaConfig.withDefaultScope should always set the default scope

### ISSUE THREAD

**Issue by claudiofahey** [pravega/flink-connectors#374]
**Problem description**
`PravegaConfig.withDefaultScope` currently ignores the provided value if the scope has already been set, possibly by the environment variable PRAVEGA_SCOPE. However, this makes it impossible to change the default scope if PRAVEGA_SCOPE has been defined. The Pravega default scope is not _just_ a default value that can be overridden when creating a stream. It is also used as the scope in which all reader groups will be created.

The motivation for this change is as follows. Consider a Flink job that runs in Kubernetes with PRAVEGA_SCOPE=scope1 but which needs to read from a stream in scope2 on a different Pravega controller. When it is tries to create the reader group, it will use the controller for scope2 but the "default" scope scope1. This will fail.

This change will also eliminate the inconsistent behavior of this method compared to similar `with...` methods in the class.

**Problem location**
PravegaConfig.withDefaultScope

**Suggestions for an improvement**
Remove check:
```
if (this.defaultScope == null)
```

**Comment by crazyzhou** [comment]
@claudiofahey This issue #139 is prioritizing the environment variable and explaining the reason of this change in the spec.
