### ISSUE TITLE
Validate correctness of ByteBuffer / byte[] interchange

### ISSUE THREAD

**Issue by StephanEwen** [pravega/flink-connectors#39]
**Problem description**

The bridge between Pravega and Flink serializers switches between `ByteBuffer` and `byte[]`. It makes the assumption that the provided byte buffers are always heap-backed and that the payload of the byte buffer is the complete backing array (no position / mark / limit / slice).

**Problem location**

In the `FlinkPravegaUtils$FlinkDeserializer.deserialize()` method.

**Suggestions for an improvement**

We should have sanity checks that validate that the byte buffer spans the full backing array (position is zero, limit is capacity).

**Comment by EronWright** [comment]
This is fixed thanks to #42
