### ISSUE TITLE
Support schema registry serializers for the writer

### ISSUE THREAD

**Issue by crazyzhou** [pravega/flink-connectors#432]
**Problem description**
The schema registry offers a way to get the serialization format of the data in the stream. Flink connector can take advantage of it. 

**Problem location**
`FlinkPravegaWriter` and `FlinkPravegaOutputFormat`

**Suggestions for an improvement**

**Comment by chenlei677** [comment]
@crazyzhou Hello, I want to do this. Please assign to me
