### ISSUE TITLE
Implement 'fixed' event router

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#45]
**Problem description**
To use the Pravega sink, an instance of `PravegaEventRouter` must be provided.   Develop a predefined implementation, similar to `FlinkFixedPartitioner`, that maps each Flink partition to a routing key.

Consider whether it would be possible to support parallelism changes to the sink.

_This approach is one of many that could be imagined to make sense of the ordering of events produced to a stream by a Flink program.  A program may ensure that all events for a given key arrive at the same sink instance by leveraging a keyed stream, e.g. `stream.keyBy(...).addSink(..)`.  Some event-time reordering logic would also be needed to establish a per-key ordering._

See [`org.apache.flink.streaming.connectors.kafka.partitioner.FlinkFixedPartitioner`](https://ci.apache.org/projects/flink/flink-docs-release-1.3/api/java/org/apache/flink/streaming/connectors/kafka/partitioner/FlinkFixedPartitioner.html) for background.

**Suggestions**
- Evolve the `PravegaEventRouter` interface with an `open(int parallelInstanceId, int parallelInstances)` method.

**Comment by EronWright** [comment]
I filed this because I don't fully understand the behavior of keyed streams in combination with sinks.  For example, in the following program, would all events for a given key be routed to the same parallel sink instance?  

```scala
val keyedStream = env.addSource(...).keyBy(_.sensorId).setParallelism(3);
keyedStream.addSink(new FlinkPravegaWriter(..., router = _.sensorId)).setParallelism(3);
```

**Comment by StephanEwen** [comment]
When you do a `keyBy()` all the same keys are in one parallel Flink task. If they originate from different sources, then they are in the order in which the network transports them.

To make sure they all end up in the same partition in Pravega, I assume that we would always need a router, because across recoveries, the readers are probably not sticky to a segment.

**Comment by StephanEwen** [comment]
Is your suggestion to plugin a default router if the stream is keyed from Flink's perspective?

Unless you want events strictly ordered by event time, I think routing by key in the FlinkPravegaWriter alone is actually sufficient.

**Comment by EronWright** [comment]
@StephanEwen please have a look at PR #46 to advance this discussion.

**Comment by EronWright** [comment]
Closing this thanks to PR #46 which satisfies my goal of providing a rational ordering of elements per routing key.
