### ISSUE TITLE
Introduce dependency sorting in the checkstyle configurations in r0.10-flink1.10

### ISSUE THREAD

**Issue by thekingofcity** [pravega/flink-connectors#523]
**Problem description**

Noticed that some imports are not sorted in the code base, this may be introduced from constant PRs, we need to fix this in all the 0.10 branches and try to add checks to avoid further similar issues.

According to https://checkstyle.sourceforge.io/config_imports.html#CustomImportOrder_Properties

```xml
<module name="CustomImportOrder">
  <property name="sortImportsInGroupAlphabetically" value="true"/>
</module>
```

**Problem location**

checkstyle configurations

**Suggestions for an improvement**

**Comment by crazyzhou** [comment]
Closed via #524
