### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by fpj** [pravega/flink-connectors#536]
**Problem description**
The README says:

> To learn more about how to build and use the Flink Connector library, follow the connector documentation here.

"here" simply points to pravega.io, so it is not very useful. We need to add some documentation saying how to build and use. 

**Problem location**
Build documentation.

**Suggestions for an improvement**
Describe how to build.

**Comment by crazyzhou** [comment]
We tend to fix the readme document in several areas in this ticket.
1. Add a "how to build" section to guide contributors.
2. Fix the deprecated links for jfrog and add the new github packages link. and remove the support for 1.10 and add 1.13
3. Change the documentation section into "how to use" and fix the link for usage documentation. @derekm I found that this link no longer works: https://pravega.io/docs/nightly/connectors/flink-connector it used to be the rendered documentation in `documentation/src` folder. Can this be fixed quickly and consistently?
