### ISSUE TITLE
Wrong doc link in readme.md

### ISSUE THREAD

**Issue by Hoohaha** [pravega/flink-connectors#546]
**Problem description**

doc linked to org site, but the site not include guide for the connector

**Problem location**

To learn more about how to build and use the Flink Connector library, follow the connector documentation here.

More examples on how to use the connectors with Flink application can be found in Pravega Samples repository.

**Suggestions for an improvement**

please use doc/ for the link

**Comment by crazyzhou** [comment]
Thanks for raising the issue. We will fix this as part of #536 , close this for now as a duplicate
