### ISSUE TITLE
How to use such connector in pyflink

### ISSUE THREAD

**Issue by Hoohaha** [pravega/flink-connectors#547]
**Problem description**

No guide or samples to configure connectors with pyflink API.

**Problem location**

**Suggestions for an improvement**

**Comment by crazyzhou** [comment]
We are trying to build a pyflink example in the pravega-samples repository and https://github.com/pravega/pravega-samples/pull/296 is currently under review now, you can take a look and pick. I agree we still need to add some more guidance in the connector documentation

**Comment by Hoohaha** [comment]
Thanks! With these samples I am able to run simple job on flink with pravega connector.
