### ISSUE TITLE
Batch connector doesn't rewind on task failover

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#56]
**Problem description**
Flink supports a number of failover strategies when a task fails, by default a global restart of the job.   None of the restart strategies work correctly with `FlinkPravegaInputFormat` because it doesn't rewind the reader group to the start position.

**Suggestions for an improvement**
- Discard the reader group state upon a global restart.  
- Validate that the job is configured to use the global failover strategy.

**Additional Background**
The restart procedure for an input format normally works as follows:
1. `InputFormat::new` is called by the client, then serialized into a job graph.
2. `InputFormat::configure` is called once by the JM when the execution graph is built.
3. `InputFormat::createInputSplits` is called once by the JM when the execution graph is built.
4. `InputFormat::getInputSplitAssigner(splits)` is called for each execution (incl. `resetForNewExecution`)
5. `InputSplitAssigner::getNextInputSplit` is called by the JM to produce a split for processing by an idle task.

In words, the 'assigner' is the iterator and is reset by the 'global' failover strategy using `resetForNewExecution`.

**Comment by fpj** [comment]
As I understand the description, this issue is about implementing the missing mechanism in the connector, not about a missing feature in Pravega, is it right?

The Pravega reader group has the notion of checkpoints, which can be used to rewind to a previous position.

**Comment by tzulitai** [comment]
@EronWright I'll apply a PR for this issue.

**Comment by tzulitai** [comment]
Hi @EronWright! I've proposed a fix for this issue: https://github.com/pravega/flink-connectors/pull/77

**Comment by EronWright** [comment]
It is becoming clear that the true fix is to use the Pravega batch API - see #65

**Comment by tzulitai** [comment]
This is now also fixed after 5eea41a74c543f859e0ab12894fb7122c4f2bb99.
Closing this.
