### ISSUE TITLE
Pravega txn API changes

### ISSUE THREAD

**Issue by fpj** [pravega/flink-connectors#60]
**Problem description**
In this commit:

https://github.com/pravega/pravega/commit/fc2791739e21fa49600d58dd5c43a06c79f6e78b

we changed the txn API to remove the various timeouts in the signature. For now, we have moved them to configuration, but we should expect some further changes.

**Problem location**
Sink connector.

**Suggestions for an improvement**
Change the use of txns according to the API changes.

**Comment by EronWright** [comment]
Fixed
