### ISSUE TITLE
Increase Default Transaction Lease to 600 seconds

### ISSUE THREAD

**Issue by maddisondavid** [pravega/flink-connectors#617]
**Problem description**
Pravega 0.10.1 increased default transaction lease (timeout) from 120 (2 minutes) seconds to 600 seconds (10 minutes).  The connector should be updated to this new default value.

**References**
- https://github.com/pravega/pravega/pull/6120
- https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/util/Config.java#L183-L184

**Problem location**
https://github.com/pravega/flink-connectors/blob/ec7ce0448a0605c9950e988bd01d6a4d47bcda01/src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java#L35

**Suggestions for an improvement**
Increase value to 600 seconds

**Comment by crazyzhou** [comment]
This issue should be fixed on master branch, and then cherry-pick to all 0.11 and 0.10 branches
