### ISSUE TITLE
FlinkPravegaReader must synchronize on checkpoint lock

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#63]
**Problem description**
A source function that supports checkpointing must synchronize on `ctx.getCheckpointLock()` as documented in [`SourceFunction`](https://ci.apache.org/projects/flink/flink-docs-release-1.3/api/java/org/apache/flink/streaming/api/functions/source/SourceFunction.html).

**Comment by fpj** [comment]
I suppose this is following the instructions here, yes?

https://ci.apache.org/projects/flink/flink-docs-master/api/java/org/apache/flink/streaming/api/functions/source/SourceFunction.html
