### ISSUE TITLE
In the manual-install.md, the Java version is wrong

### ISSUE THREAD

**Issue by chenlei677** [pravega/flink-connectors#636]
**Problem description**
Pravega needs to be compiled in the Java 11 environment, but the manual-install.md document describes Java 8

**Problem location**
 manual-install.md

**Suggestions for an improvement**
Modify the Java version mentioned in the document

**Comment by chenlei677** [comment]
@crazyzhou Hello, I have created a new Issue, please help me to take a look. Thanks

**Comment by crazyzhou** [comment]
The `manual-install.md` is located in Pravega project instead of the connector: https://github.com/pravega/pravega/blob/37f71056304f9b08ce4c17eda505a13dc401c057/documentation/src/docs/deployment/manual-install.md

You can create an issue there and we will help to fix. Thanks.
Closing this issue
