### ISSUE TITLE
Use single threaded executor in FlinkPravegaWriter

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#66]
**Problem description**
The non-transactional writer uses a larger thread pool than necessary for handling write completion callbacks.   

**Suggestions for an improvement**
Use a single threaded executor to reduce the number of created threads and to reduce contention.  The body of the callback synchronizes on the internal writer anyway, so having numerous threads simply increases contention.

**Comment by fpj** [comment]
This one sounds like a simple enough change, it makes sense to include it in the upcoming release.
