### ISSUE TITLE
Develop a unit test for FlinkPravegaReader

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#68]
**Problem description**
The `FlinkPravegaReader` has a test `FlinkPravegaReaderTest` that is best understood as an integration test.   Coverage is too low.

**Suggestions for an improvement**
- Rename `FlinkPravegaReader` to `FlinkPravegaReaderITCase`.
- Develop a unit test that uses a mock Pravega `EventStreamReader`.

**Comment by tzulitai** [comment]
@EronWright, I would gladly take this issue.

Also, I assume that this together with #67 should subsume #51?

**Comment by EronWright** [comment]
@tzulitai sounds great, would you mind following the style seen in #76 ?

**Comment by tzulitai** [comment]
Sure, no problem 👌

**Comment by EronWright** [comment]
This is fixed
