### ISSUE TITLE
FlinkPravegaWriter cannot be flushed following a write error

### ISSUE THREAD

**Issue by EronWright** [pravega/flink-connectors#70]
**Problem description**
When `close` or `flush` is called after a write that has failed internally, the method will stall forever.

**Problem location**
The problem is due to bad accounting of pending writes based on `pendingWritesCount`.  The `flush`  method waits for the count to reach zero, but the count is not properly decremented on error.  ([ref](https://github.com/pravega/flink-connectors/blob/r0.1/src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java#L162))

**Suggestions for an improvement**
Decrement the write count irrespective of success or failure.

**Comment by fpj** [comment]
Why is the write failing? Could you post the error?

**Comment by EronWright** [comment]
@fpj I hit the problem while developing a unit test for the writer.  I don't think the specific error is significant.    Take a look at the referenced code block, observing that the `pendingWritesCount` is not decremented on error, thus causing the subsequent `flush` to wait forever for `pendingWritesCount` to reach zero.
