### ISSUE TITLE
Implement metrics for the Sink API

### ISSUE THREAD

**Issue by crazyzhou** [pravega/flink-connectors#705]
**Problem description**
With #460 , the new sink interface needs to expose certain metrics.

**Problem location**
Sink API

**Suggestions for an improvement**
Add numRecordsOut, numBytesOut, refer to current Flink code and https://github.com/apache/flink/commit/545fd7a9e306b2fb32532701bdc80314d315c7c6

**Comment by derekm** [comment]
@crazyzhou -- We have need for something like this in Data Importer tests. We implemented our own Accumulators, which are easy to get for running jobs, but we can only accumulate "events read", not "events written."

**Comment by crazyzhou** [comment]
@derekm -- Thanks for the info, we will prioritize this feature next, but this only works on the new Sink API, while the data importer uses the legacy `FlinkPravegaWriter` API now, you need to upgrade to the new `PravegaSink` to use this feature when it's done.
