### ISSUE TITLE
Use `DeliveryGuarantee` enum as sink configuration

### ISSUE THREAD

**Issue by fyang86** [pravega/flink-connectors#709]
**Problem description**
Flink has already provided a enum `DeliveryGuarantee` to describe the delivery guarantee that our sink uses. We should leverage it instead of the current `PravegaWriterMode` enum.

**Problem location**
`PravegaWriterMode`, Sink

**Suggestions for an improvement**

**Comment by crazyzhou** [comment]
For this task, we need to mark the writer mode API deprecated, and keep its compatibility for this release for now. We will consider removing the writer mode in the next one or two releases.

**Comment by crazyzhou** [comment]
As the new Sink API is still marked experimental, we decide not changing the old Sink API to keep the compatibility, and directly change to use the `DeliveryGuarantee` in the new Sink API.
