### ISSUE TITLE
master-branch-connector ready for use?

### ISSUE THREAD

**Issue by cloudcompute** [pravega/flink-connectors#716]
Is the flink connector under master branch still under development or stable enough so that we can use in production?

Thanks

**Comment by crazyzhou** [comment]
Yes, it is still under development, master branch is tracking the latest version of Flink and Pravega.
We also have internal longevity tests to make sure it can be used in production.

**Comment by cloudcompute** [comment]
@crazyzhou 

Ty for the response. Can we still use it for development purposes, for this purpose, I hope it is stable enough?

Few more questions.. 

a. Which companies are using Pravega in production? Like Kafka is so popular, why has Pravega not picked up, is it because of marketing? Pravega has an auto-scaling feature while Kafka 

b. How much minimum amount of RAM and CPU does Pravega require to function properly? When it auto-scales, does it automatically consume the available memory or do we need to set some upper limit?

c. Can we use Pravega for event sourcing? 

Thanks once again.

**Comment by crazyzhou** [comment]
Yes, we would suggest using the releases in production, and master branch for dev purposes. We have tests to make sure it's stable.

a. We have a few enterprise customers that using Pravega in production.
b. For the resource usage recommendation, it depends on your deploy mode(standalone/distributed) and load, here is some useful docs for sizing: https://cncf.pravega.io/docs/v0.14.0-SNAPSHOT/admin-guide/segmentstore-memory/. When auto-scale happens, the load will be distributed onto more segment containers, which means more resources to handle that load spike, but it still cannot exceed the upper limit of the total resource.
c. Yes

**Comment by cloudcompute** [comment]
Are you aware of any library that uses 
Thanks.
