### ISSUE TITLE
Fix batch connector to support Pravega segment truncation

### ISSUE THREAD

**Issue by vijikarthi** [pravega/flink-connectors#92]
**Problem description**
The SegmentInfo API has changed with this new commit from Pravega which is causing the batch connector code compilation to fail. Fix the API call accordingly.
https://github.com/pravega/pravega/commit/be358929db2f3e1b52f408b155ed2e37d88f910b

**Problem location**
https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java#L140

**Comment by EronWright** [comment]
@vijikarthi add me as a reviewer, thanks
